### PR TITLE
redirect via form

### PR DESCRIPTION
**Pull request by bradfordcondon**
address issue #229 

I handle everything except `tripal_elasticsearch_update_index` which isnt on a form so not sure what to do about that: thoughts @mboudet ?

### CODE REVIEW

**Comment by mboudet** [comment]
tripal_elasticsearch_create_index() is called by two forms, so I would remove the drupal_goto() from it, and add $form_state['redirect'] to the forms calling it.

**Comment by bradfordcondon** [comment]
I've done that:

```php
function tripal_elasticsearch_indexing_form_submit($form, &$form_state) {
  //Create the new index
  tripal_elasticsearch_create_index($form_state['values']);
  $form_state['redirect'] = ['admin/tripal/extension/tripal_elasticsearch/indices'];
}
```

its `tripal_elasticsearch_update_index` which isnt called directly via a form and therefore doesnt have form_state passed but is instead a `menu` defined callback:

```php
  $items[$url . '/indices/update/%'] = [
    'title' => 'Update Index',
    'page callback' => 'tripal_elasticsearch_update_index',
    'page arguments' => [6],
    'access arguments' => ['administer tripal elasticsearch'],
    'file' => 'includes/tripal_elasticsearch.indices.form.inc',
    'file_path' => drupal_get_path('module', 'tripal_elasticsearch'),
    'type' => MENU_CALLBACK,
    'weight' => 1,
  ];
```

**Comment by mboudet** [comment]
Oh, you're right! This one is a but more complicated, since it's actually supposed redirect users.
I feel like since it's basically a big wrapper for "GeneSearchIndexJob::generateDispatcherJobs(TRUE);", it might be ok to leave as it is... most of it's job is to parse the input and do the proper redirection, and I don't think it can be done without drupal_goto. 

Another way might be to fully separate the redirection part and processing part, but since there are only one possible function to call, I feel like it would be too much.

**Comment by bradfordcondon** [comment]
do you need to use `tripal_elasticsearch_update_index` programmatically?  If not maybe we can leave it as is.

**Comment by mboudet** [comment]
I can probably get by with directly calling "GeneSearchIndexJob::generateDispatcherJobs(TRUE);" if needed.
The main thing I wanted to avoid was re-implementing whole functions for a module which is supposed to be only a rest API.
Thank you for the pull request, it will make it easier to update the module!

**Comment by mboudet** [comment]
Any news about merging this PR? I'd like to push a new release for python-tripal.

**Comment by mboudet** [comment]
I tested the create index (update and delete too) form for entities and tables.
I also tested the tuning form, and the create search block form without any issues.
The only one I did not test was the 'create a new connection' form.

(Then again, since setting $form_state['redirect'] is the 'proper' way, I don't think there will be any issues)

**Comment by almasaeed2010** [comment]
Great! Thanks for testing!

**Pull request merged**
